# Generated by Django 4.2.2 on 2024-06-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_date_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="user",
            new_name="owner",
        ),
    ]
