# Generated by Django 4.2.2 on 2024-07-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_rename_owner_payment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("CASH", "Наличными"), ("TRANSFER", "Перевод на счет")],
                default="TRANSFER",
                help_text="Введите способ оплаты",
                max_length=30,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
