# Generated by Django 4.2.2 on 2024-07-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ("title",),
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.AlterModelOptions(
            name="well",
            options={
                "ordering": ("title",),
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
    ]
